name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '18 1 * * 5'
  workflow_dispatch: { }

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45.2

  test:
    name: Test all packages on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
      fail-fast: false
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'

    - name: Build
      run: go build -v ./...

    - name: Set up Tor
      run: |
        brew update
        brew install tor obfs4proxy

    - name: Test
      run: |
        go test -count=1 -coverprofile=coverage.out -covermode=atomic ./...
        go tool cover -func coverage.out -o cover.out
        cat cover.out

    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out,./cover.out
        verbose: true