name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '18 1 * * 5'
  workflow_dispatch: { }

jobs:
  test-ubuntu:
    name: Test all packages on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'

    - name: Build
      run: go build -v ./...

    - name: Set up Tor
      run: |
        sudo apt update
        sudo apt install -y tor obfs4proxy

    - name: Test
      env:
        TORNADO_TEST_TORRC_OPTIONS: ${{ secrets.TORNADO_TEST_TORRC_LINUX_OPTIONS }}
      run: |
        go test -v -cover ./... -coverprofile coverage.out -coverpkg ./...
        go tool cover -func coverage.out -o coverage.out

    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        verbose: true

  test-macos:
    name: Test all packages on macos-latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'

    - name: Build
      run: go build -v ./...

    - name: Set up Tor
      run: |
        brew update
        brew install tor obfs4proxy

    - name: Test
      env:
        TORNADO_TEST_TORRC_OPTIONS: ${{ secrets.TORNADO_TEST_TORRC_MACOS_OPTIONS }}
      run: |
        go test -v -cover ./... -coverprofile coverage.out -coverpkg ./...
        go tool cover -func coverage.out -o coverage.out

    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        verbose: true